### ISSUE TITLE
Copy accents as references to reduce filesize

### ISSUE THREAD

**Issue by nermink99** [nermink99/Nerko#2]
The OTF file is today quite large, because the accents are duplicated in each accented glyph. So: 
1. copy the accents as references
2. Copy foreground to background
3. Delete the accent on the Fore layer
4. Paste the accent-reference and scale and fit it to keep the design consistent

**Comment by felipesanches** [comment]
This would be really good. Are you still planning to do it, @nermink99 ?

**Comment by nermink99** [comment]
@felipesanches from what I remember, all of this was complete while working with @davelab6

**Comment by felipesanches** [comment]
great!

**Comment by nermink99** [comment]
Still to be done
